disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_newline
  - trailing_whitespace
  - trailing_comma
  - opening_brace
  - identifier_name

line_length: 250

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 200
  error: 250

function_parameter_count:
  warning: 10
  error: 15

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

warning_threshold: 50

custom_rules:

  comments_space:
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  
  empty_closure_params:
    included: ".*.swift"
    name: "Empty closure params"
    regex: '\{ (\(\) -> Void in)$'
    message: "`() -> Void in` should be avoided"
    severity: warning
  
  print_using:
    regex: 'print\('
    message: "Print decrease performance of the app"
    severity: warning

  class_protocol:
    regex: ': class'
    message: "Use Anyobject instead"
    severity: warning
